Update RV2 to use Clang 17
ARM-software/CMSIS-RTOS2_Validation pull request #56
Opened 2023-10-26 09:26 UTC by JonatanAntoni

2023-11-23 14:16 UTC, VladimirUmek requested changes
Please also update REDME.md

CI is not working - do we wait till next toolbox release or do we implement workflow workaround?

2023-11-23 14:16 UTC, VladimirUmek commented on Layer/Target/CM33_FP/RTE/Device/IOTKit_CM33_FP_VHT/RTE_Device.h
Renaming CM3_VHT -> CM33_FP?

2023-11-23 15:56 UTC, JonatanAntoni commented on Layer/Target/CM3/RTE/Device/CMSDK_CM3_VHT/RTE_Device.h
This is only git artifact.

2023-11-24 08:25 UTC, VladimirUmek commented on Project/.clangd
This file probably shouldn't be here?

2023-11-24 08:46 UTC, JonatanAntoni commented on Project/.clangd
True, good catch!

2023-11-24 14:46 UTC, VladimirUmek commented on Project/README.md
> + ./Project $ {VHT_MODEL} -f ../Layer/Target/{DEVICE}/model_-config.txt -a Validation.{RTOS}+{DEVICE}_{COMPILER}/Validation.{RTOS}+{DEVICE}_OutDir/Validation.axf
{VHT_MODEL} should be {AVH_MODEL} as per table below

2023-11-24 14:56 UTC, JonatanAntoni commented on Project/README.md
> + ./Project $ {VHT_MODEL} -f ../Layer/Target/{DEVICE}/model_-config.txt -a Validation.{RTOS}+{DEVICE}_{COMPILER}/Validation.{RTOS}+{DEVICE}_OutDir/Validation.axf
```suggestion
 ./Project $ {AVH_MODEL} -f ../Layer/Target/{DEVICE}/model_-config.txt -a Validation.{RTOS}+{DEVICE}_{COMPILER}/Validation.{RTOS}+{DEVICE}_OutDir/Validation.axf
```

2023-11-24 15:43 UTC, VladimirUmek approved these changes
Looks good! Thanks again!

2023-11-24 15:48 UTC, merged